<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

Kirki::add_section( 'pure_code', array(
	'title' => esc_attr__( 'Code', 'pure' ),
	'panel' => 'pure_panel',
) );

Kirki::add_field( 'pure', array(
	'type'        => 'text',
	'settings'    => 'code_gtm',
	'label'       => esc_attr__( 'Google Tag Manager ID (GTM-XXXX)', 'pure' ),
	'description' => esc_attr__( 'We recommend using Google Tag Manager to manage tag and custom script of you website.', 'pure' ),
	'section'     => 'pure_code',
	'transport'   => 'postMessage',
) );

Kirki::add_field( 'pure', array(
	'type'      => 'textarea',
	'settings'  => 'code_head',
	'label'     => esc_attr__( 'Code before </head>', 'pure' ),
	'section'   => 'pure_code',
	'transport' => 'postMessage',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'textarea',
	'settings' => 'code_body',
	'label'    => esc_attr__( 'Code before </body>', 'pure' ),
	'section'  => 'pure_code',
) );

Kirki::add_field( 'pure', array(
	'type'            => 'textarea',
	'settings'        => 'code_analytics',
	'label'           => esc_attr__( 'Google Analytics code', 'pure' ),
	'section'         => 'pure_code',
	'transport'       => 'postMessage',
	'active_callback' => array(
		array(
			'setting'  => 'code_gtm',
			'operator' => '==',
			'value'    => '',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'            => 'textarea',
	'settings'        => 'code_livechat',
	'label'           => esc_attr__( 'Livechat code', 'pure' ),
	'section'         => 'pure_code',
	'transport'       => 'postMessage',
	'active_callback' => array(
		array(
			'setting'  => 'code_gtm',
			'operator' => '==',
			'value'    => '',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'text',
	'settings'  => 'fb_page_id',
	'label'     => esc_attr__( 'Facebook Page ID', 'pure' ),
	'section'   => 'pure_code',
	'transport' => 'postMessage',
) );

Kirki::add_field( 'pure', array(
	'type'      => 'text',
	'settings'  => 'fb_app_id',
	'label'     => esc_attr__( 'Facebook App ID', 'pure' ),
	'section'   => 'pure_code',
	'transport' => 'postMessage',
) );

add_action( 'template_redirect', 'pure_core_theme_options_code_hooks' );
function pure_core_theme_options_code_hooks() {

	add_action( 'wp_head', function () {

		echo pure_get_option( 'code_analytics' );
		echo pure_get_option( 'code_head' );
	} );

	add_action( 'wp_footer', function () {

		echo pure_get_option( 'code_livechat' );
		echo pure_get_option( 'code_body' );
	} );

	add_action( 'pure_after_head_open', function () {

		if ( !pure_get_option( 'code_gtm' ) ) {
			return;
		}
		?>
        <!-- Google Tag Manager -->
        <script>(function (w, d, s, l, i) {
                w[l] = w[l] || [];
                w[l].push({
                    'gtm.start':
                        new Date().getTime(), event: 'gtm.js'
                });
                var f = d.getElementsByTagName(s)[0],
                    j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
                j.async = true;
                j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j, f);
            })(window, document, 'script', 'dataLayer', '<?php echo pure_get_option( 'code_gtm' ) ?>');</script>
        <!-- End Google Tag Manager -->
		<?php
	} );

	add_action( 'pure_before', function () {

		if ( !pure_get_option( 'code_gtm' ) ) {
			return;
		}
		if ( pure_get_option( 'code_gtm' ) ) {
			?>
            <!-- Google Tag Manager (noscript) -->
            <noscript>
                <iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo pure_get_option( 'code_gtm' ) ?>"
                        height="0" width="0" style="display:none;visibility:hidden"></iframe>
            </noscript>
            <!-- End Google Tag Manager (noscript) -->
			<?php
		}
	}, 1 );

	add_action( 'wp_footer', function () {

		if ( !pure_get_option( 'fb_page_id' ) ) {
			return;
		}
		?>

        <div class="fb-customerchat"
             page_id="<?php echo esc_attr( pure_get_option( 'fb_page_id' ) ) ?>"
             theme_color="<?php echo esc_attr( pure_get_option( 'primary_color' ) ) ?>"
        >
        </div>
		<?php

	} );

}
