<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

Kirki::add_config( 'pure', array(
	'capability'  => 'edit_theme_options',
	'option_type' => 'theme_mod'         ,
) );

Kirki::add_panel( 'pure_panel', array(
    'priority'    => 10,
    'title'       => __( 'VietMoz Site', 'pure' ),
) );

function pure_kirki_styling( $config ) {
	return wp_parse_args( array(
		'logo_image'   => 'http://vietmoz.edu.vn/wp-content/uploads/2015/06/logo.png',
//		'color_accent' => '#0091EA',
//		'color_back'   => '#FFFFFF',
	), $config );
}
add_filter( 'kirki_config', 'pure_kirki_styling' );