<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

Kirki::add_section( 'pure_footer', array(
	'title' => esc_attr__( 'Footer', 'pure' ),
		'panel' => 'pure_panel',
) );

Kirki::add_field( 'pure', array(
	'type'      => 'background',
	'settings'  => 'footer_bg',
	'label'     => esc_attr__( 'Footer BG', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_bg' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element' => '.site-footer',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'footer_text_color',
	'label'     => esc_attr__( 'Footer Text Color', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_text_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.site-footer',
			'property' => 'color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'footer_heading_color',
	'label'     => esc_attr__( 'Footer Heading Color', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_heading_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6, .site-footer .h1, .site-footer .h2, .site-footer .h3, .site-footer .h4, .site-footer .h5, .site-footer .h6',
			'property' => 'color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'footer_link_color',
	'label'     => esc_attr__( 'Footer Link Color', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_link_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.site-footer a',
			'property' => 'color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'footer_link_hover_color',
	'label'     => esc_attr__( 'Footer Link Hover Color', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_link_hover_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.site-footer a:hover',
			'property' => 'color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'dimension',
	'settings'  => 'footer_text_size',
	'label'     => esc_attr__( 'Footer Text Size', 'pure' ),
	'section'   => 'pure_footer',
	'transport' => 'auto',
	'default'   => pure_get_default_option( 'footer_text_size' ),
	'default'   => '14px',
	'output'    => array(
		array(
			'element'  => '.site-footer',
			'property' => 'font-size',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'dimension',
	'settings'  => 'footer_heading_size',
	'label'     => esc_attr__( 'Footer Heading Size', 'pure' ),
	'section'   => 'pure_footer',
	'default'   => pure_get_default_option( 'footer_heading_size' ),
	'transport' => 'auto',
	'default'   => '16px',
	'output'    => array(
		array(
			'element'  => '.site-footer h1, .site-footer h2, .site-footer h3, .site-footer h4, .site-footer h5, .site-footer h6, .site-footer .h1, .site-footer .h2, .site-footer .h3, .site-footer .h4, .site-footer .h5, .site-footer .h6',
			'property' => 'font-size',
		),
	),
) );
