<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

Kirki::add_section( 'pure_info', array(
	'title' => esc_attr__( 'Infomation', 'pure' ),
	'panel' => 'pure_panel',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_name',
	'label'    => esc_attr__( 'Company name', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'textarea',
	'settings' => 'info_desc',
	'label'    => esc_attr__( 'Company Description', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'            => 'text',
	'settings'        => 'info_hotline',
	'label'           => esc_attr__( 'Hotline', 'pure' ),
	'section'         => 'pure_info',
	'partial_refresh' => array(
		'info_hotline' => array(
			'selector'        => '.hotline .number',
			'render_callback' => 'pure_cz_hotline',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'            => 'text',
	'settings'        => 'info_time',
	'label'           => esc_attr__( 'Work Time', 'pure' ),
	'section'         => 'pure_info',
	'partial_refresh' => array(
		'info_time' => array(
			'selector'        => '.hotline .work-time',
			'render_callback' => 'pure_cz_worktime',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_telephone',
	'label'    => esc_attr__( 'Telephone', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_email',
	'label'    => esc_attr__( 'Email', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_street_address',
	'label'    => esc_attr__( 'Street Address', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_district',
	'label'    => esc_attr__( 'District', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_city',
	'label'    => esc_attr__( 'City', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_facebook',
	'label'    => esc_attr__( 'Facebook', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_youtube',
	'label'    => esc_attr__( 'Youtube', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_google_plus',
	'label'    => esc_attr__( 'Google Plus', 'pure' ),
	'section'  => 'pure_info',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'info_instagram',
	'label'    => esc_attr__( 'Instagram', 'pure' ),
	'section'  => 'pure_info',
) );

function pure_cz_hotline() {

	echo pure_get_option( 'info_hotline' );
}

function pure_cz_worktime() {

	echo pure_get_option( 'info_time' );
}
