<?php
/**
 *
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

Kirki::add_section( 'pure_styling', array(
	'title' => esc_attr__( 'Styling', 'pure' ),
	'panel' => 'pure_panel',
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'primary_color',
	'label'     => esc_attr__( 'Primary Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'primary_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'a:focus,a:hover,.entry-content a,.site-header.desktop.v2 .site-navigation>ul>li.btn.sfHover a,.site-header.desktop.v2 .site-navigation>ul>li.btn:hover a,.site-header.desktop.v2 .site-navigation>ul>li.current-menu-item>a,.site-header.desktop.v2 .site-navigation>ul>li.sfHover>a,.term-description a,.btn.alt,.button.alt,button.alt,input[type=button].alt,input[type=reset].alt,input[type=submit].alt,.pagination .nav-links>:hover,.page-links>a:hover,.page-links>span:not(.page-links-title)',
			'property' => 'color',
		),
		array(
			'element'  => '.color-primary-color,.color-primary-color--before:before,.color-primary-color--after:after,.color-primary-color--before--hover:hover:before,.color-primary-color--hover:hover,.color-primary-color--after--hover:hover:after,button.alt, input[type="button"].alt, input[type="reset"].alt, input[type="submit"].alt, .button.alt, .btn.alt,.slick-next:hover,.slick-prev:hover,.widget.widget_course_info_widget .widget-title',
			'property' => 'color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => 'abbr:after,acronym:after,.btn,.button,button,input[type=button],input[type=reset],input[type=submit],.pagination .nav-links>.current,.site-header.desktop.v2 .site-navigation>ul>li>a:before,.comment-list .reply:hover,.slick-dots li.slick-active button:before,.widget_price_filter .ui-slider .ui-slider-handle,.widget_price_filter .ui-slider .ui-slider-range,.site-navigation.desktop .sf-menu li.danh-muc-san-pham',
			'property' => 'background-color',
		),
		array(
			'element'  => '.bg-primary-color,.bg-primary-color--after:after,.bg-primary-color--before:before,.bg-primary-color--after--hover:hover:after,.bg-primary-color--hover:hover,.bg-primary-color--before--hover:hover:before',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => 'abbr:before,acronym:before',
			'property' => 'border-right-color',
		),
		array(
			'element'  => '.btn,.button,button,input[type=button],input[type=reset],input[type=submit],.btn.alt,.button.alt,button.alt,input[type=button].alt,input[type=reset].alt,input[type=submit].alt,.pagination .nav-links>.current,.comment-list .reply:hover',
			'property' => 'border-color',
		),
		array(
			'element'  => '.hotline svg.icon path',
			'property' => 'fill',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'secondary_color',
	'label'     => esc_attr__( 'Secondary Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'secondary_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.entry-content a:focus,.entry-content a:hover,.term-description a:focus,.term-description a:hover',
			'property' => 'color',
		),
		array(
			'element'  => '.color-secondary-color,.color-secondary-color--before:before,.color-secondary-color--after:after,.color-secondary-color--before--hover:hover:before,.color-secondary-color--hover:hover,.color-secondary-color--after--hover:hover:after',
			'property' => 'color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => '.btn:hover,.button:hover,button:hover,input[type=button]:hover,input[type=reset]:hover,input[type=submit]:hover,.site-header.desktop.v2,.site-header.mobile.v2,.site-header.desktop.v2 .site-navigation ul ul li:hover',
			'property' => 'background-color',
		),
		array(
			'element'  => '.bg-secondary-color,.bg-secondary-color--after:after,.bg-secondary-color--before:before,.bg-secondary-color--hover:hover,.bg-secondary-color--after--hover:hover:after,.bg-secondary-color--before--hover:hover:before',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => '.btn:hover,.button:hover,button:hover,input[type=button]:hover,input[type=reset]:hover,input[type=submit]:hover',
			'property' => 'border-color',
		),
		array(
			'element'  => '.btn-1 button, .btn-1 input[type="button"], .btn-1 input[type="reset"], .btn-1 input[type="submit"], .btn-1 .button, .btn-1 .btn',
			'property' => 'border-bottom-color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'text_color',
	'label'     => esc_attr__( 'Text Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'text_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'body,.pagination .nav-links>*,.page-links>:not(.page-links-title)',
			'property' => 'color',
		),
		array(
			'element'  => '.color-text-color,.color-text-color--hover:hover',
			'property' => 'color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => '.slick-dots li button:before',
			'property' => 'background-color',
		),
		array(
			'element'  => '.bg-text-color,.bg-text-color--hover:hover',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'heading_color',
	'label'     => esc_attr__( 'Heading Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'heading_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'a,.h1,.h2,.h3,.h4,.h5,.h6,h1,h2,h3,h4,h5,h6',
			'property' => 'color',
		),
		array(
			'element'  => '.color-heading-color,.color-heading-color--hover:hover',
			'property' => 'color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => '.bg-heading-color,.bg-heading-color--hover:hover,.bg-heading-color,.bg-heading-color--before:before,.bg-heading-color--after:after',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'border_color',
	'label'     => esc_attr__( 'Border Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'border_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'hr,thead th,.site-header.desktop,.comment-list .comment-body,.border-bottom',
			'property' => 'border-bottom-color',
		),
		array(
			'element'  => '.border-top,.site-header.v1 .lower',
			'property' => 'border-top-color',
		),
		array(
			'element'  => '.border-left',
			'property' => 'border-left-color',
		),
		array(
			'element'  => '.border-right',
			'property' => 'border-right-color',
		),
		array(
			'element'  => '.border,td,th,.pagination .nav-links>*,input:not([type]),input[type=color],input[type=date],input[type=datetime-local],input[type=datetime],input[type=email],input[type=month],input[type=number],input[type=password],input[type=search],input[type=tel],input[type=text],input[type=time],input[type=url],input[type=week],textarea,input:not([type]):disabled:hover,input[type=color]:disabled:hover,input[type=date]:disabled:hover,input[type=datetime-local]:disabled:hover,input[type=datetime]:disabled:hover,input[type=email]:disabled:hover,input[type=month]:disabled:hover,input[type=number]:disabled:hover,input[type=password]:disabled:hover,input[type=search]:disabled:hover,input[type=tel]:disabled:hover,input[type=text]:disabled:hover,input[type=time]:disabled:hover,input[type=url]:disabled:hover,input[type=week]:disabled:hover,textarea:disabled:hover,.site-navigation.desktop .sf-menu ul,.site-navigation.desktop .sf-menu ul a,.comment-respond,.comment-list .reply, .caldera-grid .caldera_forms_form .form-control,.wp-caption',
			'property' => 'border-color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'meta_color',
	'label'     => esc_attr__( 'Meta Color', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'meta_color' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.bg-meta-color,.bg-meta-color--hover:hover',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
		array(
			'element'  => '.widget_price_filter .price_slider_wrapper .ui-widget-content',
			'property' => 'background-color',
		),
		array(
			'element'  => '.entry-meta-before,.product_meta',
			'property' => 'color',
		),
		array(
			'element'  => '.color-meta-color, .color-meta-color--hover:hover,.slick-next,.slick-prev',
			'property' => 'color',
			'suffix'   => ' !important',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'primary_bg',
	'label'     => esc_attr__( 'Primary BG', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'primary_bg' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element' => 'body,.slideout-panel',
			'property' => 'background-color',
		),
		array(
			'element' => '.bg-primary-bg,.bg-primary-bg--hover:hover',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
		array(
			'element' => '.pagination .nav-links>.current, button, input[type="button"], input[type="reset"], input[type="submit"], .button, .btn, input[type="button"]:hover, input[type="reset"]:hover, input[type="submit"]:hover, .button:hover, .btn:hover, .color-primary-bg,.color-primary-bg--hover:hover',
			'property' => 'color',
			'suffix'   => ' !important',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'color',
	'settings'  => 'secondary_bg',
	'label'     => esc_attr__( 'Secondary BG', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => pure_get_default_option( 'secondary_bg' ),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element' => '.color-secondary-bg,.color-secondary-bg--hover:hover',
			'property' => 'color',
			'suffix'   => ' !important',
		),
		array(
			'element' => '.bg-secondary-bg,.bg-secondary-bg--hover:hover',
			'property' => 'background-color',
			'suffix'   => ' !important',
		),
		array(
			'element' => '.comment-respond,.comment-list .reply,.tech-spec table tr:nth-child(odd),.wp-caption',
			'property' => 'background-color',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'dimension',
	'settings'  => 'button_height',
	'label'     => esc_attr__( 'Button Height', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => '40px',
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'button, input[type="button"], input[type="reset"], input[type="submit"],.button,.btn,.site-navigation.desktop .sf-menu > li.btn > a,.caldera-grid input[type="button"],.caldera-grid input[type="reset"],.caldera-grid input[type="submit"]',
			'property' => 'line-height',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'      => 'dimension',
	'settings'  => 'button_radius',
	'label'     => esc_attr__( 'Button Radius', 'pure' ),
	'section'   => 'pure_styling',
	'default'   => '2px',
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => 'button, input[type="button"], input[type="reset"], input[type="submit"],.button,.btn',
			'property' => 'border-radius',
		),
	),
) );
