<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

if ( !class_exists( 'WooCommerce' ) ) {
	return;
}

Kirki::add_panel( 'pure_woocommerce', array(
	'title' => esc_attr__( 'WooCommerce', 'pure' ),
	'panel' => 'pure_panel',
) );

Kirki::add_section( 'pure_woo_general', array(
	'title' => esc_attr__( 'General', 'pure' ),
	'panel' => 'pure_woocommerce',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'wc_general_warranty_link',
	'label'    => esc_attr__( 'Terms of Warranty Link', 'pure' ),
	'section'  => 'pure_woo_general',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'wc_general_return_link',
	'label'    => esc_attr__( 'Terms of Return Link', 'pure' ),
	'section'  => 'pure_woo_general',
) );

Kirki::add_section( 'pure_woo_single', array(
	'title' => esc_attr__( 'Single', 'pure' ),
	'panel' => 'pure_woocommerce',
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'wc_add_to_cart_text',
	'label'    => esc_attr__( 'Add to cart text', 'pure' ),
	'default'  => pure_get_default_option( 'wc_add_to_cart_text' ),
	'section'  => 'pure_woo_single',
	'partial_refresh' => array(
		'add_to_cart_text' => array(
			'selector'        => '.single_add_to_cart_button',
			'render_callback' => 'pure_cz_add_to_cart_text',
		),
	),
) );

Kirki::add_field( 'pure', array(
	'type'     => 'text',
	'settings' => 'wc_add_to_cart_additional_text',
	'label'    => esc_attr__( 'Add to cart additional text', 'pure' ),
	'section'  => 'pure_woo_single',
) );

Kirki::add_field( 'pure', array(
	'type'            => 'text',
	'settings'        => 'buying_guide_link',
	'label'           => esc_attr__( 'Purchase help link', 'pure' ),
	'default'         => pure_get_default_option( 'buying_guide_link' ),
	'section'         => 'pure_woo_single',
) );

Kirki::add_field( 'pure', array(
	'type'            => 'editor',
	'settings'        => 'wc_single_promotion',
	'label'           => esc_attr__( 'Promotion', 'pure' ),
	'section'         => 'pure_woo_single',
) );

function pure_cz_add_to_cart_text() {

	echo pure_get_option( 'add_to_cart_text' );
}

