<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

remove_action( 'pure_before_loop', 'pure_loop_wrapper_open', 10 );
remove_action( 'pure_loop', 'pure_standard_loop' );
remove_action( 'pure_after_loop', 'pure_loop_wrapper_close', 10 );

add_action( 'pure_loop', 'pure_404' );
function pure_404() {

	pure_tag( array(
		'open'    => '<article class="entry pure-404">',
		'context' => 'entry-404',
	) );

	?>

    <div class="pure-404__upper">
        <div class="pure-404__icon color-primary-color">404</div>

        <h2 class="pure-404__title">
			<?php echo __( 'Page not found', 'pure' ); ?>
        </h2>
        <p class="pure-404__subtitle">
			<?php echo __( 'Sorry, the page you requested can not be found!', 'pure' ); ?>
        </p>
    </div>

    <div class="pure-404__middle">
        <a class="pure-404__back-to-home" href="<?php echo home_url(); ?>"
           title="<?php echo get_bloginfo( 'name' ); ?>">
			<?php echo __( '<i class="far fa-caret-left"></i> Back to home', 'pure' ); ?>
        </a>
        <div class="pure-404__search">
			<?php get_search_form(); ?>
        </div>
    </div>

    <hr/>

    <div class="pure-404__under">

		<?php
		$custom_args  = array( 'post_type' => 'page', 'posts_per_page' => 3 );
		$custom_query = new WP_Query( $custom_args );
		if ( $custom_query->have_posts() ):
			?>
            <div class="pure-404__page">
                <h3 class="pure-404__page-title">
					<?php echo __( 'Page', 'pure' ); ?>
                </h3>
                <ul>
					<?php while ( $custom_query->have_posts() ): ?>
						<?php $custom_query->the_post(); ?>
                        <li>
                            <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>
                        </li>
					<?php endwhile; ?>
                </ul>
            </div>
			<?php wp_reset_postdata(); ?>
		<?php endif; ?>

		<?php
		$custom_args  = array( 'posts_per_page' => 3 );
		$custom_query = new WP_Query( $custom_args );
		if ( $custom_query->have_posts() ):
			?>
            <div class="pure-404__news">
                <h3 class="pure-404__news-title">
					<?php echo __( 'News', 'pure' ); ?>
                </h3>
                <ul>
					<?php while ( $custom_query->have_posts() ): ?>
						<?php $custom_query->the_post(); ?>
                        <li>
                            <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>
                        </li>
					<?php endwhile; ?>
                </ul>
            </div>
			<?php wp_reset_postdata(); ?>
		<?php endif; ?>

        <div class="pure-404__categories">
            <h3 class="pure-404__categories-title">
				<?php echo __( 'Categories', 'pure' ); ?>
            </h3>
            <ul>
				<?php wp_list_categories( array( 'number' => 3, 'title_li' => '', 'hierarchical' => false ) ); ?>
            </ul>
        </div>
    </div>
	<?php
	pure_tag( array(
		'close'   => '</article>',
		'context' => 'entry-404',
	) );
}

pure();