<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

pure_wrap( 'site-inner', 'close', true, false );

pure_tag( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

do_action( 'pure_before_footer' );
/**
 * Hook: pure_footer
 *
 * @hooked pure_footer_open - 5
 * @hooked pure_footer_widget_area - 10
 * @hooked pure_copyright - 15
 * @hooked pure_footer_close - 1000
 */
do_action( 'pure_footer' );
do_action( 'pure_after_footer' );

pure_tag( array(
	'context' => 'site-container',
	'close'   => '</div>',
) );

do_action( 'pure_after' );

wp_footer();

pure_tag( array(
	'close'   => '</body>',
	'context' => 'body',
) );

?>
</html>
