<?php
/**
 * Template name: Blank Page
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

remove_action( 'pure_loop', 'pure_standard_loop' );
add_action( 'pure_loop', 'the_content' );

pure();