<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

pure_tag( array(
	'open'    => '<aside %s>',
	'context' => 'sidebar-secondary',
) );

do_action( 'pure_before_sidebar_secondary');
do_action( 'pure_sidebar_secondary'       );
do_action( 'pure_after_sidebar_secondary' );

pure_tag( array(
	'close'    => '</aside>',
	'context' => 'sidebar-secondary',
) );
