<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

/**
 * Logo shorthand function.
 *
 * @param $context
 *
 * @return null
 */
function pure_logo( $context = 'desktop', $h = true )
{

	$title_tag = 'div';
	if ( pure_is_root_page() && $h ) {
		$title_tag = 'h1';
	}

	pure_tag( array(
		'open'    => "<{$title_tag} %s>",
		'context' => 'site-title',
	) );

	$logo = sprintf(
		'<img itemprop="logo" src="%s" alt="%s" />',
		pure_get_option( "{$context}_logo", apply_filters( "pure_{$context}_logo_url", PURE_IMAGES_URL . '/logo.png' ) ),
		get_bloginfo( 'name' )
	);

	printf(
		'<a href="%s" title="%s">%s</a>',
		home_url(),
		get_bloginfo( 'name' ),
		apply_filters( "pure_{$context}_logo_html", $logo )
	);

	pure_tag( array(
		'close'   => "</{$title_tag}>",
		'context' => 'site-title',
	) );

	return null;
}
