<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

/**
 * Contextually return or echo wrap div.
 *
 * @param string $context
 * @param string $type
 * @param bool   $echo
 * @param bool   $inner
 *
 * @return string
 */
function pure_wrap( $context, $type = 'open', $echo = true, $inner = false ) {

	if ( $inner ) {
		$output = '</div></div>';

		if ( 'open' === $type ) {
			$output = sprintf( '<div %s><div class="inner">', pure_attr( 'wrap' ) );
		}
	} else {

		$output = '</div>';

		if ( 'open' === $type ) {
			$output = sprintf( '<div %s>', pure_attr( 'wrap' ) );
		}
	}

	$output = apply_filters( "pure_wrap-{$context}", $output, $type );

	if ( $echo ) {
		echo $output;

		return null;
	} else {
		return $output;
	}

}

/**
 * Filtered sidebar layout.
 */
function pure_get_sidebar_layout() {

	if ( is_page_template( 'page-blank.php' ) ) {
		return 'c';
	} else {
		return apply_filters( 'pure_sidebar_layout', 'cs' );
	}
}
