<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

/**
 * Post Thumbnail HTML.
 *
 * @param int $width
 * @param int $height
 */
function pure_entry_thumbnail($size = array())
{

	$default_size = apply_filters('pure_entry_thumbnail_default_size', array(
		'height' => 300,
		'width' => 400,
	));

	$size = wp_parse_args($size, $default_size);

	if (has_post_thumbnail()) :

		pure_tag( array(
			'open'    => '<div %s>',
			'context' => 'entry-thumbnail',
		) );

		printf(
			'<a href="%1$s" title="%2$s"><img src="%3$s" alt="%2$s" /></a>',
			get_permalink(),
			get_the_title(),
			pure_resize(get_post_thumbnail_id(), $size['width'], $size['height'], true)
		);

		pure_tag( array(
			'close'   => '</div>',
			'context' => 'entry-thumbnail',
		) );

	endif;
}
