<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

function pure_snippet_info() {

	?>
    <div class="snippet-info" itemscope itemtype="http://schema.org/Organization">
		<?php if ( pure_get_option( 'info_name' ) ): ?>
            <div itemprop="name" class="info__name">
				<?php if ( pure_get_option( 'info_google_plus' ) ): ?>
                    <a href="<?php echo pure_get_option( 'info_google_plus' ); ?>"
                       title="<?php echo pure_get_option( 'info_name' ); ?>">
						<?php echo pure_get_option( 'info_name' ); ?>
                    </a>
				<?php else: ?>
					<?php echo pure_get_option( 'info_name' ); ?>
				<?php endif; ?>
            </div>
		<?php endif; ?>
		<?php if ( pure_get_option( 'info_desc' ) ): ?>
            <div class="info__desc" itemprop="description">
				<?php echo pure_get_option( 'info_desc' ); ?>
            </div>
		<?php endif; ?>
        <div class="info__address" itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
			<?php if ( pure_get_option( 'info_street_address' ) ) : ?>
                <span class="icon-wrap"><i class="far fa-map-marker-alt color-primary-color"></i></span>
                <span itemprop="streetAddress"><?php echo pure_get_option( 'info_street_address' ) ?></span>,
			<?php endif; ?>
			<?php if ( pure_get_option( 'info_district' ) ) : ?>
                <span itemprop="addressLocality"><?php echo pure_get_option( 'info_district' ) ?></span>,
			<?php endif; ?>
			<?php if ( pure_get_option( 'info_city' ) ) : ?>
                <span itemprop="addressRegion"><?php echo pure_get_option( 'info_city' ) ?></span>
			<?php endif; ?>
        </div>
		<?php if ( pure_get_option( 'info_telephone' ) ) : ?>
            <div class="info__telephone">
                <span class="icon-wrap"><i class="far fa-phone color-primary-color"></i></span>
                <span itemprop="telephone">
					<?php echo pure_get_option( 'info_telephone' ) ?>
				</span>
            </div>
		<?php endif; ?>
		<?php if ( pure_get_option( 'info_hotline' ) ) : ?>
            <div class="info__hotline">
                <span class="icon-wrap"><i class="far fa-mobile color-primary-color"></i></span>
                <span itemprop="telephone">
					<?php echo pure_get_option( 'info_hotline' ) ?>
				</span>
            </div>
		<?php endif; ?>
		<?php if ( pure_get_option( 'info_email' ) ) : ?>
            <div class="info__email">
                <span class="icon-wrap"><i class="far fa-envelope color-primary-color"></i></span>
                <span itemprop="email">
					<?php echo pure_get_option( 'info_email' ) ?>
				</span>
            </div>
		<?php endif; ?>
    </div>
	<?php
}

if ( !function_exists( 'pure_snippet_hotline' ) ) {
	function pure_snippet_hotline( $class = '', $hide_work_time = false, $icon = true ) {

		$hotline = pure_get_option( 'info_hotline' );
		if ( !$hotline ) {
			return;
		}
		?>

        <div class="hotline <?php echo esc_attr( $class ); ?>">
            <a href="tel:<?php echo preg_replace( '/[^0-9.]+/', '', $hotline ); ?>">
				<?php if ( $icon ) : ?>
                    <svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                         version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 88 88.4"
                         style="enable-background:new 0 0 88 88.4;" xml:space="preserve">
                        <g transform="translate(0,-952.36218)">
                            <path d="M44,952.1c-24.3,0-44,19.7-44,44c0,24.3,19.7,44,44,44c1.1,0,2-0.9,2-2c0-1.1-0.9-2-2-2c0,0,0,0-0.1,0   c-22.1,0-40-17.9-40-40s17.9-40,40-40s40,17.9,40,40c0,13.2-5.7,24.4-16.5,31.9c-1.8-0.1-3.9-1-5.8-2.7c-1.6-1.4-3-3.1-4-5   c1-0.5,2-1,3.1-1.7c1.9-1.1,3.9-3.7,2.9-5.4c-1.5-2.6-5.2-7-6.9-8.5s-4.3,0.4-5.8,1.2c-4,2.2-5.1,3.9-9.6-4l-3.3-5.7   c-4.5-7.9-2.5-8,1.4-10.3c1.5-0.9,4.4-2.3,4-4.4c-0.4-2.1-2.4-7.7-3.9-10.2c-1-1.8-4.2-1.3-6.2-0.2c-11.2,6.5-12.4,12.5-3.3,28.3   l4.6,7.9c7.1,12.2,12.1,16.1,19.2,14.3c1.2,2.6,3.1,4.9,5.2,6.7c2.6,2.2,5.7,3.7,8.9,3.7c0.4,0,0.8-0.1,1.1-0.3   c12.3-8.1,18.9-21,18.9-35.7C88,971.8,68.3,952.1,44,952.1z"/>
                        </g>
                    </svg>
				<?php endif; ?>
                <div class="inner">
					<span class="number color-primary-color">
						<?php echo esc_html( $hotline ); ?>
					</span>
					<?php if ( !$hide_work_time && $time = pure_get_option( 'info_time' ) ): ?>
                        <span class="work-time color-meta-color">
						<?php echo esc_html( $time ); ?>
					</span>
					<?php endif; ?>
                </div>
            </a>
        </div>
		<?php
	}
}
