<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

/**
 * Register sidebar wrapper function.
 *
 * @param array  $args Sidebar agruments.
 * @param string $tag  Heading tag of widget title.
 *
 * @return string
 */
function pure_register_sidebar( $args, $tag = 'h4' ) {

	$defaults = array(
		'before_widget' => pure_tag( array(
			'open'    => '<section id="%%1$s" class="widget %%2$s"><div class="widget-inner">',
			'context' => 'widget-wrap',
			'echo'    => false,
		) ),
		'after_widget'  => pure_tag( array(
			'close'   => '</div></section>' . "\n",
			'context' => 'inner-wrap',
			'echo'    => false,
		) ),
		'before_title'  => '<' . $tag . ' class="widget-title"><span>',
		'after_title'   => "</span></" . $tag . ">\n",
	);

	$defaults = apply_filters( 'pure_register_sidebar_defaults', $defaults, $args );

	$args = wp_parse_args( $args, $defaults );

	return register_sidebar( $args );
}

add_action( 'pure_setup', 'pure_register_widgets_areas' );
/**
 * Register all sidebars.
 */
function pure_register_widgets_areas() {

	add_action( 'widgets_init', 'pure_register_sidebars' );
	add_action( 'widgets_init', 'pure_register_footer_widgets' );
}

function pure_register_sidebars() {

	$widget_title_tag = apply_filters( 'pure_sidebar_widget_title_tag', 'h3' );

	pure_register_sidebar( array(
		'id'          => 'sidebar-primary',
		'name'        => __( 'Sidebar', 'pure' ),
		'description' => __( 'Primary sidebar area.', 'pure' ),
	), $widget_title_tag );
	pure_register_sidebar( array(
		'id'          => 'sidebar-secondary',
		'name'        => __( 'Secondary Sidebar', 'pure' ),
		'description' => __( 'Secondary sidebar area. Not every theme support this.', 'pure' ),
	), $widget_title_tag );
	pure_register_sidebar( array(
		'id'          => 'sidebar-bottom',
		'name'        => __( 'Bottom Sidebar', 'pure' ),
		'description' => __( 'Bottom sidebar area. Not every theme support this.', 'pure' ),
	), $widget_title_tag );
}

/**
 * Return filtered number of footer widgets.
 */
function pure_get_footer_widgets_count() {

	return apply_filters( 'pure_footer_widgets_count', 4 );
}

/**
 * Register Footer widgets if supported.
 */
function pure_register_footer_widgets() {

	$footer_widgets = pure_get_footer_widgets_count();

	if ( !$footer_widgets || !is_numeric( $footer_widgets ) ) {
		return;
	}

	$footer_widget_title_tag = apply_filters( 'pure_footer_widget_title_tag', 'h4' );

	$footer_widgets = (int)$footer_widgets;

	$counter = 1;

	while ( $counter <= $footer_widgets ) {

		pure_register_sidebar( array(
			'id'          => sprintf( 'footer-%d', $counter ),
			'name'        => sprintf( __( 'Footer %d', 'pure' ), $counter ),
			'description' => sprintf( __( 'Footer %d widget area.', 'pure' ), $counter ),
		), $footer_widget_title_tag );

		$counter++;
	}
}

/**
 * Template for default widget area content.
 *
 * @param string $name Name of the widget area.
 */
function pure_default_widget_area_content( $name ) {

	pure_tag( array(
		'open' => '<section class="widget widget_text">',
	) );

	echo '<div class="widget-inner">';

	echo sprintf( '<%1$s class="widget-title">%2$s</%1$s>', 'h4', esc_html( $name ) );
	echo '<div class="textwidget"><p>';

	printf( __( 'This is the %s. You can add content to this area by visiting your <a href="%s">Widgets Panel</a> and adding new widgets to this area.', 'pure' ), $name, admin_url( 'widgets.php' ) );

	echo '</p></div>';

	echo '</div>';

	pure_tag( array(
		'close' => '</section>',
	) );

}

/**
 * Check if location active before output sidebar.
 */
function pure_dynamic_sidebar( $location, $name ) {

	if ( !is_active_sidebar( $location ) && current_user_can( 'edit_theme_options' ) ) {
		pure_default_widget_area_content( $name );
	} else {
		dynamic_sidebar( $location );
	}
}
