<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_shortcode( 'hotline', 'pure_hotline_shortcode' );
/**
 * Simple wrapper
 */
function pure_hotline_shortcode( $atts ) {

	$defaults = array(
		'class'          => '',
		'hide_work_time' => '1',
	);

	$atts = shortcode_atts( $defaults, $atts, 'hotline' );

	$hotline = pure_get_option( 'info_hotline' );

	ob_start();
	pure_snippet_hotline( $atts[ 'class' ], $atts[ 'hide_work_time' ] );

	$output = ob_get_clean();

	return apply_filters( 'pure_hotline_shortcode', $output, $atts );

}

add_shortcode( 'info', 'pure_info_shortcode' );
/**
 * @return string
 */
function pure_info_shortcode() {

	ob_start();
	pure_snippet_info();

	return ob_get_clean();
}

add_shortcode( 'logo', 'pure_logo_shortcode' );
/**
 * @return string
 */
function pure_logo_shortcode() {

	ob_start();
	?>

    <div class="info__logo">
		<?php pure_logo( 'desktop', false ); ?>
    </div>
	<?php
	return ob_get_clean();
}
