<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_shortcode( 'section', 'pure_section_shortcode' );
/**
 * Simple wrapper
 */
function pure_section_shortcode( $atts, $content = null ) {

	$defaults = array(
		'id'    => '',
		'class' => '',
		'style' => '',
	);

	$atts = shortcode_atts( $defaults, $atts, 'section' );

	$content = do_shortcode( $content );

	$output = '<div class="sc-section ' . $atts[ 'class' ] . '" id="' . $atts[ 'id' ] . '" style="' . $atts[ 'style' ] . '">' . $content . '</div>';

	return apply_filters( 'pure_section_shortcode', $output, $atts );

}

add_shortcode( 'flex', 'pure_flex_shortcode' );
/**
 * Simple wrapper
 */
function pure_flex_shortcode( $atts, $content = null ) {

	$defaults = array(
		'id'    => '',
		'class' => '',
		'style' => '',
	);

	$atts = shortcode_atts( $defaults, $atts, 'flex' );

	$content = do_shortcode( $content );

	$output = '<div class="sc-flex ' . $atts[ 'class' ] . '" id="' . $atts[ 'id' ] . '" style="' . $atts[ 'style' ] . '">' . $content . '</div>';

	return apply_filters( 'pure_flex_shortcode', $output, $atts );

}

add_shortcode( 'item', 'pure_item_shortcode' );
/**
 * Simple wrapper
 */
function pure_item_shortcode( $atts, $content = null ) {

	$defaults = array(
		'id'    => '',
		'class' => '',
		'style' => '',
	);

	$atts = shortcode_atts( $defaults, $atts, 'item' );

	$content = do_shortcode( $content );

	$output = '<div class="sc-item ' . $atts[ 'class' ] . '" id="' . $atts[ 'id' ] . '" style="' . $atts[ 'style' ] . '">' . $content . '</div>';

	return apply_filters( 'pure_item_shortcode', $output, $atts );

}
