<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_shortcode( 'social_icon', 'pure_social_icon_shortcode' );
/**
 * Responsive embeded youtube video.
 */
function pure_social_icon_shortcode( $atts ) {

	$social = [
		'facebook'    => pure_get_option( 'info_facebook' ),
		'youtube'     => pure_get_option( 'info_youtube' ),
		'google-plus' => pure_get_option( 'info_google_plus' ),
		'instagram'   => pure_get_option( 'info_instagram' ),
	];

	ob_start()

	?>

    <ul class="sc-social-icon">
		<?php foreach ( $social as $name => $url ) {
			printf( '<li><a href="%s"><i class="fab fa-%s"></i></a></li>', $url, $name );
		} ?>
    </ul>

	<?php
	return ob_get_clean();
}
