<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_shortcode( 'video', 'pure_video_shortcode' );
/**
 * Responsive embeded youtube video.
 */
function pure_video_shortcode( $atts ) {

	$defaults = array(
		'url' => '',
	);

	$atts = shortcode_atts( $defaults, $atts, 'video' );

	global $wp_embed;
	$output = sprintf( '<div class="responsive-video">%s</div>', $wp_embed->run_shortcode( '[embed]' . $atts[ 'url' ] . '[/embed]' ) );

	return apply_filters( 'pure_video_shortcode', $output, $atts );

}
