<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'pure_footer', 'pure_footer_open', 5 );
/**
 * Opening tag for footer.
 */
function pure_footer_open() {

	pure_tag( array(
		'open'    => '<footer %s>',
		'context' => 'site-footer',
	) );
}

add_action( 'pure_footer', 'pure_footer_close', 1000 );
/**
 * Closing tag for footer.
 */
function pure_footer_close() {

	pure_tag( array(
		'close'   => '</footer>',
		'context' => 'site-footer',
	) );
}

add_action( 'pure_footer', 'pure_footer_widgets_area', 10 );
/**
 * Render main footer widgets area.
 */
function pure_footer_widgets_area() {

	$footer_widgets = pure_get_footer_widgets_count();

	if ( !$footer_widgets || !is_numeric( $footer_widgets ) ) {
		return;
	}

	$footer_widgets = (int)$footer_widgets;

	$counter = 1;

	pure_tag( array(
		'context' => 'footer-widget-areas',
		'open'    => '<div %s>',
	) );

	pure_wrap( 'footer-widget-areas', 'open', true, true );

	while ( $counter <= $footer_widgets ) {

		pure_tag( array(
			'context' => 'footer-widget-area',
			'open'    => '<div %s>',
			'params'  => array(
				'id' => sprintf( 'footer-%d', $counter ),
			),
		) );

		pure_dynamic_sidebar( 'footer-' . $counter, sprintf( __( 'Footer %d', 'pure' ), $counter ) );

		pure_tag( array(
			'context' => 'footer-widget-area',
			'close'   => '</div>',
		) );

		$counter++;
	}

	pure_wrap( 'footer-widget-areas', 'close', true, true );

	pure_tag( array(
		'context' => 'footer-widget-areas',
		'close'   => '</div>',
	) );
}

add_action( 'pure_footer', 'pure_copyright', 15 );
/**
 * Render copyright text.
 */
function pure_copyright() {

	$enable = apply_filters( 'pure_copyright_enable', true );

	if ( !$enable ) {
		return;
	}

	pure_tag( array(
		'open'    => '<div %s>',
		'context' => 'copyright',
	) );

	pure_wrap( 'copyright' );

	printf(
		__( '<div class="copyright-content">Copyright &copy; <span itemprop="copyrightYear">%1$s</span> <span itemprop="copyrightHolder" itemscope itemtype="https://schema.org/Person"><a href="%4$s" title="%2$s" itemprop="name">%2$s</a></span>. Design by <a href="%3$s" title="Web Design by VietMoz">VietMoz</a>.</div>', 'pure' ),
		esc_html( date( 'Y' ) ),
		esc_html( get_bloginfo( 'name' ) ),
		esc_url( 'http://thietkeweb.vietmoz.com' ),
		esc_url( home_url() )
	);

	do_action( 'pure_copyright_additional_content' );

	pure_wrap( 'copyright', 'close' );

	pure_tag( array(
		'close'   => '</div>',
		'context' => 'copyright',
	) );
}

add_action( 'pure_footer', 'pure_back_to_top' );
/**
 * Hook back to top button to footer.
 * Only display button in footer.
 */
function pure_back_to_top() {

	$enable = apply_filters( 'pure_back_to_top_enable', true );

	if ( !$enable ) {
		return;
	}

	?>
    <span class="back-to-top bg-primary-color"><i class="far fa-arrow-up color-primary-bg"></i></span>
	<?php
}

add_action( 'wp_footer', 'pure_photoswipe_markup' );
/**
 * Photoswipe markup
 */
function pure_photoswipe_markup() {

	?>
    <!-- Root element of PhotoSwipe. Must have class pswp. -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <!-- Background of PhotoSwipe.
			 It's a separate element as animating opacity is faster than rgba(). -->
        <div class="pswp__bg"></div>

        <!-- Slides wrapper with overflow:hidden. -->
        <div class="pswp__scroll-wrap">

            <!-- Container that holds slides.
				PhotoSwipe keeps only 3 of them in the DOM to save memory.
				Don't modify these 3 pswp__item elements, data is added later on. -->
            <div class="pswp__container">
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
            <div class="pswp__ui pswp__ui--hidden">

                <div class="pswp__top-bar">

                    <!--  Controls are self-explanatory. Order can be changed. -->

                    <div class="pswp__counter"></div>

                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                    <button class="pswp__button pswp__button--share" title="Share"></button>

                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                    <!-- element will get class pswp__preloader--active when preloader is running -->
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                            <div class="pswp__preloader__cut">
                                <div class="pswp__preloader__donut"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div>
                </div>

                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>

                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>

                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>

            </div>

        </div>

    </div>
	<?php
}

add_action( 'pure_after_footer', 'pure_call_button' );
/**
 * Call button on mobile.
 * Display at lower left conner.
 */
function pure_call_button() {

	$hotline = pure_get_option( 'info_hotline' );
	if ( !$hotline ) {
		return;
	}
	echo '<a href="tel:' . $hotline . '" class="call-button bg-primary-color bg-secondary-color--hover color-primary-bg color-primary-bg--hover">';
	echo '<i class="far fa-phone"></i>';
	echo '</a>';
}

add_action( 'wp_footer', 'pure_search_holder' );
/**
 * Pure search holder.
 * Hold search form and background to pop up when user click on search triggers.
 */
function pure_search_holder() {

	echo '<div class="pure-search-holder">';
	echo '<div class="inner">';
	get_search_form();
	echo '</div>';
	echo '</div>';
}