<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'pure_before_loop', 'pure_title', 5 );
/**
 * Output title for non single pages.
 */
function pure_title() {

	if( is_singular() ) {
		return;
	}

	pure_tag( array(
		'context' => 'title',
		'open'    => '<h1 %s>',
	) );

	if ( is_tag() ) :
		single_tag_title();
	elseif ( is_home() ) :
		bloginfo('name');
	elseif ( is_category() ) :
		single_cat_title();
	elseif ( is_tax() ) :
		single_term_title();
	elseif ( is_day() ) :
		printf( get_the_date() );
	elseif ( is_month() ) :
		printf( get_the_date( _x( 'F Y', 'monthly archives date format', 'pure' ) ) );
	elseif ( is_year() ) :
		printf( get_the_date( _x( 'Y', 'yearly archives date format', 'pure' ) ) );
	elseif ( is_post_type_archive() ) :
		post_type_archive_title();
	elseif ( is_search() ) :
		printf( esc_html__( 'Search Results for: %s', 'pure' ), '<span>' . get_search_query() . '</span>' );
	elseif( is_404() ):
		echo __('Error 404: Page not found!','pure');
	endif;

	pure_tag( array(
		'context' => 'title',
		'close'   => '</h1>',
	) );
}

