<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'pure_doctype', 'pure_doctype' );
/**
 * HMTL5 doctype and opening markup.
 */
function pure_doctype() {

?><!doctype html>
<html <?php language_attributes( 'html' ); ?>>
<?php pure_tag( array( 'context' => 'head', 'open' => '<head %s>' ) ); ?>
<meta charset="<?php bloginfo( 'charset' ); ?>"/>
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php
do_action( 'pure_after_head_open' );
}

add_action( 'get_header', 'pure_head_control' );
/**
 * Control header meta WP puts in `head`.
 */
function pure_head_control() {

	remove_action( 'wp_head', 'wp_generator' );
}

add_action( 'pure_title', 'pure_meta_title' );
/**
 * Title tag.
 */
function pure_meta_title() {

	if ( get_theme_support( 'title-tag' ) ) {
		return;
	}

	echo '<title>';
	wp_title( '' );
	echo '</title>';
}

add_action( 'pure_meta', 'pure_meta_pingback' );
/**
 * Pingback meta tag.
 */
function pure_meta_pingback() {

	echo '<link rel="pingback" href="' . esc_attr( get_bloginfo( 'pingback_url' ) ) . '" />' . "\n";
}

add_action( 'wp_head', 'pure_meta_name' );
/**
 * Site name meta tag.
 */
function pure_meta_name() {

	if ( !pure_is_root_page() ) {
		return;
	}

	printf( '<meta itemprop="name" content="%s" />' . "\n", esc_attr( get_bloginfo( 'name' ) ) );

	return null;
}

add_action( 'wp_head', 'pure_meta_url' );
/**
 * Site URL meta tag.
 */
function pure_meta_url() {

	if ( !pure_is_root_page() ) {
		return;
	}

	printf( '<meta itemprop="url" content="%s" />' . "\n", esc_url( trailingslashit( home_url() ) ) );
}

add_action( 'pure_header', 'pure_header_open', 5 );
/**
 * Opening tag for header.
 */
function pure_header_open() {

	pure_tag( array(
		'open'    => '<header %s>',
		'context' => 'site-header',
	) );
}

add_action( 'pure_header', 'pure_header_close', 15 );
/**
 * Closing tag for header.
 */
function pure_header_close() {

	pure_tag( array(
		'close'   => '</header>',
		'context' => 'site-header',
	) );
}

add_action( 'pure_header', 'pure_header' );
if ( !function_exists( 'pure_header' ) ) {
	/**
	 * Main header.
	 */
	function pure_header() {

		pure_wrap( 'site-header', 'open', true, true );

		pure_logo();

		pure_tag( array(
			'open'    => '<div %s>',
			'close'   => '</div>',
			'context' => 'pure-flex-space',
		) );

		pure_tag( array(
			'open'    => '<nav %s>',
			'context' => 'site-navigation',
		) );
		wp_nav_menu( array(
			'theme_location' => 'primary',
			'container'      => '',
			'menu_class'     => 'sf-menu',
		) );

		pure_tag( array(
			'close'   => '</nav>',
			'context' => 'site-navigation',
		) );

		pure_wrap( 'site-header', 'close', true, true );
	}
}

add_action( 'pure_after_header', 'pure_mobile_header' );

if ( !function_exists( 'pure_mobile_header' ) ) {
	/**
	 * Mobile header.
	 */
	function pure_mobile_header() {

		echo '<div class="site-header mobile">';
		echo '<div class="wrap">';
		echo '<div class="inner">';

		pure_logo( 'mobile', false );

		pure_tag( array(
			'open'    => '<div %s>',
			'close'   => '</div>',
			'context' => 'pure-flex-space',
		) );

		echo '<span class="search-toggler"><i class="fa fa-search"></i></span>';

		echo '<div class="bg-primary-bg search-holder">';
		get_search_form();
		echo '</div>';

		pure_tag( array(
			'open'    => '<button %s>',
			'close'   => '</button>',
			'context' => 'menu-toggler',
			'content' => apply_filters( 'pure_menu_toggler_icon', sprintf( '<i class="%s"></i>', 'far fa-bars' ) ),
			'params'  => array(
				'id' => 'menu-toggler',
			),
		) );

		echo '</div>';
		echo '</div>';
		echo '</div>';
	}
}
