<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_filter( 'body_class', 'pure_sidebar_layout_class' );
/**
 * Add body class to handle sidebar layout.
 */
function pure_sidebar_layout_class( $classes ) {

	$classes[] = pure_get_sidebar_layout();

	return $classes;
}

add_action( 'template_redirect', 'pure_get_sidebars' );
/**
 * Hook sidebars to website by selected layout.
 */
function pure_get_sidebars() {

	$layout = pure_get_sidebar_layout();

	if ( 'c' === $layout || 'f' === $layout ) {
		return;
	}

	add_action( 'pure_after_content', 'pure_get_sidebar' );

	if ( 'cs' !== $layout && 'sc' !== $layout ) {
		add_action( 'pure_after_content', 'pure_get_sidebar_secondary' );
	}
}

/**
 * Render the primary sidebar.
 */
function pure_get_sidebar() {

	get_sidebar();
}

/**
 * Render the secondary sidebar.
 */
function pure_get_sidebar_secondary() {

	get_sidebar( 'secondary' );
}

add_action( 'template_redirect', 'pure_output_breadcrumbs' );
/**
 * Output breadcrumbs to filtered positions.
 */
function pure_output_breadcrumbs() {

	if ( pure_is_root_page() || is_page_template( 'page-blank.php' ) ) {
		return;
	}

	$position = apply_filters( 'pure_breadcrumbs_position', 'pure_after_header' );

	add_action( $position, 'pure_breadcrumbs' );
}

/**
 * Breadcrumbs HTML.
 */
function pure_breadcrumbs() {

	$breadcrumb_markup_open = '<div class="breadcrumbs ' . apply_filters( 'pure_breadcrumbs_classes', '' ) . '"><div class="wrap"><div class="inner">';

	if ( class_exists( 'WPSEO_Breadcrumbs' ) ) {
		yoast_breadcrumb( $breadcrumb_markup_open, '</div></div></div>' );
	} elseif ( function_exists( 'yoast_breadcrumb' ) && !class_exists( 'WPSEO_Breadcrumbs' ) ) {
		yoast_breadcrumb( $breadcrumb_markup_open, '</div></div></div>' );
	}

}

add_filter( 'body_class', 'pure_button_style_class' );
function pure_button_style_class( $classes ) {

	$classes[] = apply_filters( 'pure_button_style_class', '' );

	return $classes;
}