<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'pure_loop', 'pure_standard_loop' );
/**
 * Pure standard loop.
 */
function pure_standard_loop() {

	if ( have_posts() ) :

		do_action( 'pure_before_loop_while' );

		while ( have_posts() ) : the_post();

			pure_tag( array(
				'open'    => '<article %s>',
				'context' => 'entry',
			) );

			if( ! is_singular() ):
			// Adding insider for better style handling.
			pure_tag( array(
				'context' => 'loop__insider',
				'open'    => '<div %s>',
			));

			endif;

			/**
			 * Hook: pure_before_entry
			 *
			 * is_category()
			 * @hooked pure_loop_thumbnail - 5
			 * @hooked pure_entry_info_open - 10
			 */
			do_action( 'pure_before_entry' );

			/**
			 * Hook: pure_entry_header
			 *
			 * @hooked pure_entry_header_open  - 5
			 * @hooked pure_entry_title        - 10
			 * @hooked pure_entry_meta_before  - 12
			 * @hooked pure_social_sharing     - 15
			 * @hooked pure_entry_header_close - 100
			 */
			do_action( 'pure_entry_header' );

			do_action( 'pure_before_entry_content' );

			pure_tag( array(
				'open'    => '<div %s>',
				'context' => 'entry-content',
			) );

			/**
			 * Hook: pure_entry_content
			 *
			 * @hooked pure_entry_content - 10
			 */
			do_action( 'pure_entry_content' );

			pure_tag( array(
				'close'   => '</div>',
				'context' => 'entry-content',
			) );

			/**
			 * Hook: pure_after_entry_content
			 *
			 * @hooked pure_link_pages - 10
			 */
			do_action( 'pure_after_entry_content' );

			/**
			 * Hook: pure_entry_footer
			 *
			 * @hooked pure_entry_footer_open  - 5
			 * @hooked pure_social_sharing     - 15
			 * @hooked pure_tag_list           - 20
			 * @hooked pure_entry_footer_close - 100
			 */
			do_action( 'pure_entry_footer' );

			/**
			 * Hook: pure_after_entry
			 *
			 * is_single()
			 * @hooked pure_related_posts - 10
			 *
			 * is_category()
			 * @hooked pure_entry_info_close - 10
			 */
			do_action( 'pure_after_entry' );

			if( ! is_singular() ):
			pure_tag( array(
				'context' => 'loop__insider',
				'close'   => '</div>',
			) );
			endif;

			pure_tag( array(
				'close'   => '</article>',
				'context' => 'entry',
			) );

		endwhile;

		/**
		 * Hook: pure_after_loop_white
		 *
		 * @hooked pure_posts_nav - 10
		 */
		do_action( 'pure_after_loop_while' );

	else:
		/**
		 * Hook: pure_loop_else
		 *
		 * @hooked pure_no_posts - 10
		 */
		do_action( 'pure_loop_else' );
	endif;
}

add_action( 'pure_before_loop', 'pure_loop_wrapper_open' );
/**
 * Loop wrapper opening.
 */
function pure_loop_wrapper_open() {

	if ( is_singular() ) {
		return;
	}

	pure_tag( array(
		'context' => 'loop',
		'open'    => '<div %s>',
	) );

}

add_action( 'pure_after_loop', 'pure_loop_wrapper_close' );
/**
 * Loop wrapper closing.
 */
function pure_loop_wrapper_close() {

	if ( is_singular() ) {
		return;
	}

	pure_tag( array(
		'context' => 'loop',
		'close'   => '</div>',
	) );
}
