<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'after_setup_theme', 'pure_register_nav_menus' );
/**
 * Register menu locations.
 *
 * Does the `pure_register_nav_menus` for hooking custom locations from child theme.
 */
function pure_register_nav_menus() {

	if ( !current_theme_supports( 'pure-menus' ) ) {
		return;
	}

	$menus = get_theme_support( 'pure-menus' );

	register_nav_menus( (array)$menus[ 0 ] );

	do_action( 'pure_register_nav_menus' );
}

add_action( 'pure_after', 'pure_mobile_menu' );
/**
 * Print Mobile Menu.
 */
function pure_mobile_menu() {

	echo '<nav class="site-navigation mobile" id="slideout">';

	pure_tag( array(
		'open'    => '<div %s>',
		'context' => 'inner',
	) );

	if ( has_nav_menu( 'mobile' ) ) {
		wp_nav_menu( array(
			'theme_location' => 'mobile',
			'container'      => '',
			'walker'         => new Pure_Mobile_Menu_Walker,
		) );
	} else {
		wp_nav_menu( array(
			'theme_location' => 'primary',
			'container'      => '',
			'walker'         => new Pure_Mobile_Menu_Walker,
		) );
	}

	pure_tag( array(
		'open'    => '<button %s>',
		'close'   => '</button>',
		'context' => 'menu-toggler',
		'content' => apply_filters( 'pure_menu_close_icon', sprintf( '<i class="%s"></i>', 'far fa-arrow-left mgr10' ) ) . __( 'Close menu', 'pure' ),
	) );

	pure_tag( array(
		'close'   => '</div>',
		'context' => 'inner',
	) );

	echo '</nav>';

	return null;
}
