<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'pure_before_loop', 'pure_taxonomy_description', 7 );

function pure_taxonomy_description() {

	if ( is_category() || is_tag() || is_tax() ) {
		echo '<div class="term-description">';
		echo term_description();
		echo '</div>';
	}
}
