<?php
/**
 * Pure Framework.
 *
 * WARNING: This is part of the Pure Framework. DO NOT EDIT this file under any circumstances.
 * Please do all your modifications in a child theme.
 *
 * @package Pure
 * @author  Boong
 * @link    https://boongstudio.com/themes/pure
 */

add_action( 'wp_enqueue_scripts', 'pure_load_js' );
function pure_load_js() {

	$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG || defined( 'WP_DEBUG' ) && WP_DEBUG ? '' : '.min';

//	if ( wp_is_mobile() ) {
		wp_enqueue_script( 'slideout', PURE_JS_URL . "/slideout{$suffix}.js", array( 'jquery' ), '1.0.1', true );
//	} else {
		wp_enqueue_script( 'hoverIntent', PURE_JS_URL . "/hoverIntent{$suffix}.js", array( 'jquery' ), '1.9.0', true );
		wp_enqueue_script( 'superfish', PURE_JS_URL . "/superfish{$suffix}.js", array( 'jquery' ), '1.7.9', true );
//	}

	wp_enqueue_script( 'slick', PURE_JS_URL . "/slick{$suffix}.js", array( 'jquery' ), '1.8.0', true );

	wp_enqueue_script( 'flickity', PURE_JS_URL . "/flickity{$suffix}.js", array( 'jquery' ), '2.1.1', true );

	wp_enqueue_script( 'isotope', PURE_JS_URL . "/isotope.pkgd.min.js", array( 'jquery', 'imagesloaded' ), '3.0.5', true );

	wp_enqueue_script( 'photoswipe', PURE_JS_URL . "/photoswipe.min.js", array( 'jquery' ), '4.1.2', true );

	wp_enqueue_script( 'photoswipe-ui-default', PURE_JS_URL . "/photoswipe-ui-default.min.js", array( 'photoswipe' ), '4.1.2', true );

	wp_enqueue_script( 'font-awesome-5', PURE_JS_URL . "/fontawesome-all{$suffix}.js", array(), '5.0.8', true );

	wp_enqueue_script( PARENT_THEME_NAME, PURE_JS_URL . "/pure{$suffix}.js", array( 'jquery', 'isotope' ), PARENT_THEME_VERSION, true );


	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
